version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    command: node .
    image: api-sdk
    container_name: api-sdk
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ${ROOT_PATH}/.env:/usr/src/app/.env
      - ${ROOT_PATH}/.cam-resources.yaml:/usr/src/app/.cam-resources.yaml
