FROM balenalib/aarch64-ubuntu-node:bionic

RUN [ "cross-build-start" ]

WORKDIR /usr/src/app

RUN mkdir -p bin

ADD rtsp-simple-proxy_v0.2.14_linux_arm64.digest.fix.tar.gz ./bin

COPY package*.json ./

RUN npm install

COPY src ./src
COPY *.js *.json ./

RUN [ "cross-build-end" ]
