version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    command: node .
    image: api-sdk
    container_name: api-sdk
    env_file: .env
    environment:
      - PORT=$PORT
    ports:
      - "3000:3000"
    volumes:
      - .env:/usr/src/app/.env
