version: '3'

services:
  pgsql:
    image: postgres:12.3-alpine
    container_name: api-sdk-db
    env_file: .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d
      - ${ROOT_PATH}/pgsql/data:/var/lib/postgresql/data
    networks: [ 'edge' ]

  nodejs:
    image: dockerteamrecon/api-sdk:master-aarch64
    command: node .
    container_name: api-sdk
    env_file: .env
    network_mode: host
#    ports:
#      - "3000:3000"
#      - "8554:8554"
#      - "8050:8050/udp"
#      - "8051:8051/udp"
    volumes:
      - ${ROOT_PATH}/.env:/usr/src/app/.env
      - ${ROOT_PATH}/cam-resources.yml:/usr/src/app/.cam-resources.yml
    restart: always
    depends_on:
       - pgsql
    networks: [ 'edge' ]

networks: { edge: { } }
